# Gruvbox Red Color Scheme
# class                 border  backgr. text    indicator child_border
client.focused          #cc241d #cc241d #fbf1c7 #cc241d   #cc241d
client.focused_inactive #3c3836 #3c3836 #a89984 #3c3836   #3c3836
client.unfocused        #282828 #282828 #ebdbb2 #282828   #282828
client.urgent           #fb4934 #fb4934 #282828 #fb4934   #fb4934
client.background       #282828
