#!/usr/bin/env bash

album=$(mpc current -f "%album%")

[ -z "$album" ] && exit

song=$(mpc search album "$album" | \
rofi -dmenu -p "$album")

[ -z "$song" ] && exit

mpc clear
mpc add "$song"
mpc play
