#!/usr/bin/env bash

song=$(cat ~/.config/mpd/favorites.txt | sort -u | \
rofi -dmenu -p "Favorites")

[ -z "$song" ] && exit

mpc clear
mpc search title "$song" | head -n1 | xargs -r mpc add
mpc play
