#!/usr/bin/env bash

choice=$(printf "🔍 Search\n💿 Current Album\n📃 Queue\n❤️ Favorites" | \
rofi -dmenu -p "Music")

case "$choice" in
    "🔍 Search")
        ~/.config/i3/scripts/music/search
        ;;
    "💿 Current Album")
        ~/.config/i3/scripts/music/album
        ;;
    "📃 Queue")
        ~/.config/i3/scripts/music/queue
        ;;
    "❤️ Favorites")
        ~/.config/i3/scripts/music/favorites
        ;;
esac
