#!/usr/bin/env bash

selection=$(
{
    mpc list album
    mpc list title
} | sort -u | rofi -dmenu -i -p "Search"
)

[ -z "$selection" ] && exit

export song="$selection"

~/.config/i3/scripts/music/actions
